import card1 from "../../assets/img/card1.png"
import card2 from "../../assets/img/card2.png"
export let home = [
    {
        id: 1,
        title:"Комфорт",
        title2: "Строится",
        title3: "От 12 650 000 сум\м2",
        title4: "“Business House”",
        title5: "2- Andijon",
        title6: "Andijon.sh komolon .k ",
        title7: "Cрок сдачи: 2024",
        title8: "Коробка",
        title9: "Рассрочка 29 месяц",
        title10: "Этажи 16",
        title11: "Договорная",
        btn: "Подробнее",
        img: card1
    },
    {
        id: 2,
        title:"Комфорт",
        title2: "Строится",
        title3: "От 12 650 000 сум\м2",
        title4: "“Business House”",
        title5: "2- Andijon",
        title6: "Andijon.sh komolon .k ",
        title7: "Cрок сдачи: 2024",
        title8: "Коробка",
        title9: "Рассрочка 29 месяц",
        title10: "Этажи 16",
        title11: "Договорная",
        btn: "Подробнее",
        img: card2
    },
    {
        id: 3,
        title:"Комфорт",
        title2: "Строится",
        title3: "От 12 650 000 сум\м2",
        title4: "“Business House”",
        title5: "2- Andijon",
        title6: "Andijon.sh komolon .k ",
        title7: "Cрок сдачи: 2024",
        title8: "Коробка",
        title9: "Рассрочка 29 месяц",
        title10: "Этажи 16",
        title11: "Договорная",
        btn: "Подробнее",
        img: card1
    }, {
        id: 4,
        title:"Комфорт",
        title2: "Строится",
        title3: "От 12 650 000 сум\м2",
        title4: "“Business House”",
        title5: "2- Andijon",
        title6: "Andijon.sh komolon .k ",
        title7: "Cрок сдачи: 2024",
        title8: "Коробка",
        title9: "Рассрочка 29 месяц",
        title10: "Этажи 16",
        title11: "Договорная",
        btn: "Подробнее",
        img: card1
    },
    {
        id: 5,
        title:"Комфорт",
        title2: "Строится",
        title3: "От 12 650 000 сум\м2",
        title4: "“Business House”",
        title5: "2- Andijon",
        title6: "Andijon.sh komolon .k ",
        title7: "Cрок сдачи: 2024",
        title8: "Коробка",
        title9: "Рассрочка 29 месяц",
        title10: "Этажи 16",
        title11: "Договорная",
        btn: "Подробнее",
        img: card2
    },
    {
        id: 6,
        title:"Комфорт",
        title2: "Строится",
        title3: "От 12 650 000 сум\м2",
        title4: "“Business House”",
        title5: "2- Andijon",
        title6: "Andijon.sh komolon .k ",
        title7: "Cрок сдачи: 2024",
        title8: "Коробка",
        title9: "Рассрочка 29 месяц",
        title10: "Этажи 16",
        title11: "Договорная",
        btn: "Подробнее",
        img: card1
    },
    
]